#!/usr/bin/env bash

set -e

cd ~/dotfiles

git stash -u >/dev/null 2>&1 || true

git pull --rebase origin main

git stash pop >/dev/null 2>&1 || true

stow --restow -t ~ .

echo "Dotfiles sincronizados correctamente"
